// <auto-generated />
namespace MVCClubsWeek4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ApplicationDBContextSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplicationDBContextSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201810092307272_Application DB Context Setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
